// Seed data with all 48 products from the Excel file
// This is used when a new user registers to pre-load their catalog
// Sizes: "Bolsa Completa" = larger size, "Media Bolsa" = smaller size

export const PRODUCT_SIZES = ['Bolsa Completa', 'Media Bolsa', 'Bolsa Chica', 'Pieza', 'Litro', 'Otro'];

export const SEED_PRODUCTS = [
  { name: 'ALMENDRA CUBIERTA CON CHOCOLATE 500 GR', cost: 190, suggested_price: 240, sale_price: 250, category: 'Almendras', size: 'Bolsa Completa' },
  { name: 'ALMENDRA CUBIERTA CON CHOCOLATE 250 GR', cost: 95, suggested_price: 120, sale_price: 130, category: 'Almendras', size: 'Media Bolsa' },
  { name: 'ALMENDRA NATURAL 500 GR', cost: 145, suggested_price: 200, sale_price: 225, category: 'Almendras', size: 'Bolsa Completa' },
  { name: 'ALMENDRA NATURAL 250 GR', cost: 72.50, suggested_price: 100, sale_price: 120, category: 'Almendras', size: 'Media Bolsa' },
  { name: 'ARÁNDANO DESHIDRATADO ENCHILADO TAJÍN 500 GR', cost: 95, suggested_price: 150, sale_price: 155, category: 'Arándanos', size: 'Bolsa Completa' },
  { name: 'ARÁNDANO DESHIDRATADO ENCHILADO TAJÍN 250 GR', cost: 47.50, suggested_price: 75, sale_price: 80, category: 'Arándanos', size: 'Media Bolsa' },
  { name: 'ARÁNDANO DESHIDRATADO NATURAL 430 GR', cost: 90, suggested_price: 130, sale_price: 135, category: 'Arándanos', size: 'Bolsa Completa' },
  { name: 'ARÁNDANO DESHIDRATADO NATURAL 215 GR', cost: 45, suggested_price: 65, sale_price: 75, category: 'Arándanos', size: 'Media Bolsa' },
  { name: 'CACAHUATE GARAPIÑADO ROJO 430 GR', cost: 48, suggested_price: 70, sale_price: 80, category: 'Cacahuates', size: 'Bolsa Completa' },
  { name: 'CACAHUATE GARAPIÑADO ROJO 215 GR', cost: 24, suggested_price: 35, sale_price: 45, category: 'Cacahuates', size: 'Media Bolsa' },
  { name: 'DÁTIL 430 GR', cost: 65, suggested_price: 110, sale_price: 110, category: 'Dátiles', size: 'Bolsa Completa' },
  { name: 'DÁTIL 215 GR', cost: 32.50, suggested_price: 55, sale_price: 60, category: 'Dátiles', size: 'Media Bolsa' },
  { name: 'ENERGITAS MIX ENCHILADO 430 GR', cost: 78, suggested_price: 125, sale_price: 130, category: 'Mixes Energitas', size: 'Bolsa Completa' },
  { name: 'ENERGITAS MIX ENCHILADO 215 GR', cost: 39, suggested_price: 65, sale_price: 70, category: 'Mixes Energitas', size: 'Media Bolsa' },
  { name: 'ENERGITAS MIX FRUTA ENCHILADA 430 GR', cost: 120, suggested_price: 170, sale_price: 170, category: 'Mixes Energitas', size: 'Bolsa Completa' },
  { name: 'ENERGITAS MIX FRUTA ENCHILADA 215 GR', cost: 60, suggested_price: 85, sale_price: 85, category: 'Mixes Energitas', size: 'Media Bolsa' },
  { name: 'ENERGITAS MIX NATURAL 430 GR', cost: 78, suggested_price: 125, sale_price: 130, category: 'Mixes Energitas', size: 'Bolsa Completa' },
  { name: 'ENERGITAS MIX NATURAL 215 GR', cost: 39, suggested_price: 65, sale_price: 70, category: 'Mixes Energitas', size: 'Media Bolsa' },
  { name: 'ENERGITAS MIX SALADO 430 GR', cost: 78, suggested_price: 125, sale_price: 130, category: 'Mixes Energitas', size: 'Bolsa Completa' },
  { name: 'ENERGITAS MIX SALADO 215 GR', cost: 39, suggested_price: 65, sale_price: 70, category: 'Mixes Energitas', size: 'Media Bolsa' },
  { name: 'GRANOLA TOSTADA CON MIEL DE ABEJA 430 GR', cost: 55, suggested_price: 95, sale_price: 115, category: 'Granola', size: 'Bolsa Completa' },
  { name: 'GRANOLA TOSTADA CON MIEL DE ABEJA 215 GR', cost: 27.50, suggested_price: 47.50, sale_price: 65, category: 'Granola', size: 'Media Bolsa' },
  { name: 'MANGO DESHIDRATADO ENCHILADO 350 GR', cost: 110, suggested_price: 165, sale_price: 165, category: 'Mango', size: 'Bolsa Completa' },
  { name: 'MANGO DESHIDRATADO ENCHILADO 175 GR', cost: 55, suggested_price: 82.50, sale_price: 85, category: 'Mango', size: 'Media Bolsa' },
  { name: 'MIEL DE ABEJA 100% NATURAL 1 LITRO', cost: 145, suggested_price: 195, sale_price: 200, category: 'Miel', size: 'Litro' },
  { name: 'MINI COYOTAS DE CAJETA', cost: 30, suggested_price: 50, sale_price: 50, category: 'Dulces regionales', size: 'Pieza' },
  { name: 'MIX FRUTOS DE CAPIROTADA 500 GR', cost: 90, suggested_price: 130, sale_price: 135, category: 'Mixes Energitas', size: 'Bolsa Completa' },
  { name: 'MIX FRUTOS DE CAPIROTADA 250 GR', cost: 45, suggested_price: 65, sale_price: 70, category: 'Mixes Energitas', size: 'Media Bolsa' },
  { name: 'NUEZ GARAPIÑADA 350 GR', cost: 130, suggested_price: 180, sale_price: 185, category: 'Nueces', size: 'Bolsa Completa' },
  { name: 'NUEZ GARAPIÑADA 175 GR', cost: 65, suggested_price: 90, sale_price: 95, category: 'Nueces', size: 'Media Bolsa' },
  { name: 'NUEZ INDIA TOSTADA CON SAL 430 GR', cost: 162, suggested_price: 225, sale_price: 230, category: 'Nueces', size: 'Bolsa Completa' },
  { name: 'NUEZ INDIA TOSTADA CON SAL 215 GR', cost: 81, suggested_price: 112.50, sale_price: 120, category: 'Nueces', size: 'Media Bolsa' },
  { name: 'NUEZ PECANA NATURAL 300 GR', cost: 110, suggested_price: 160, sale_price: 155, category: 'Nueces', size: 'Bolsa Completa' },
  { name: 'NUEZ PECANA NATURAL 150 GR', cost: 55, suggested_price: 80, sale_price: 80, category: 'Nueces', size: 'Media Bolsa' },
  { name: 'PIÑA DESHIDRATADA ENCHILADA 500 GR', cost: 145, suggested_price: 195, sale_price: 200, category: 'Piña', size: 'Bolsa Completa' },
  { name: 'PIÑA DESHIDRATADA ENCHILADA 250 GR', cost: 72.50, suggested_price: 97.50, sale_price: 105, category: 'Piña', size: 'Media Bolsa' },
  { name: 'PISTACHE TOSTADO CON SAL 350 GR', cost: 145, suggested_price: 195, sale_price: 210, category: 'Pistache', size: 'Bolsa Completa' },
  { name: 'PISTACHE TOSTADO CON SAL 175 GR', cost: 72.50, suggested_price: 97.50, sale_price: 110, category: 'Pistache', size: 'Media Bolsa' },
  { name: 'JAMONCILLOS DE URES 10 PZAS', cost: 50, suggested_price: 70, sale_price: 75, category: 'Dulces regionales', size: 'Pieza' },
  { name: 'JAMONCILLOS DE URES 04 PZAS', cost: 20, suggested_price: 28, sale_price: 30, category: 'Dulces regionales', size: 'Pieza' },
  { name: 'CARNE SECA DE RES ESTILO SONORA 100 GR', cost: 100, suggested_price: 140, sale_price: 140, category: 'Carnes', size: 'Pieza' },
  { name: 'ENERGITAS MIX NATURAL 80 GR', cost: 15, suggested_price: 25, sale_price: 25, category: 'Mixes Energitas', size: 'Bolsa Chica' },
  { name: 'ENERGITAS MIX SALADO 80 GR', cost: 15, suggested_price: 25, sale_price: 25, category: 'Mixes Energitas', size: 'Bolsa Chica' },
  { name: 'ENERGITAS MIX ENCHILADO 80 GR', cost: 15, suggested_price: 25, sale_price: 25, category: 'Mixes Energitas', size: 'Bolsa Chica' },
  { name: 'ENERGITAS MIX LEGUMBRES 380 GR', cost: 55, suggested_price: 90, sale_price: 90, category: 'Mixes Energitas', size: 'Bolsa Completa' },
  { name: 'MANGO DESHIDRATADO GOURMET PULPA ENCHILADO 350 GR CHAMOY', cost: 115, suggested_price: 170, sale_price: 170, category: 'Mango', size: 'Bolsa Completa' },
  { name: 'HABAS ENCHILADAS 300 GR', cost: 45, suggested_price: 70, sale_price: 70, category: 'Otros', size: 'Bolsa Completa' },
  { name: 'CACAHUATE BOTANERO CON AJO 500 GR', cost: 55, suggested_price: 85, sale_price: 85, category: 'Cacahuates', size: 'Bolsa Completa' },
];
